/**
 * Traducción automática (inglés -> español) de los nombres de las ofertas
 * que llegan desde el proveedor. Solo se aplica a nombres de ofertas,
 * nunca a los nombres de los juegos.
 *
 * Las marcas, monedas y nombres propios se mantienen intactos.
 */

// Frases (se aplican antes que las palabras sueltas)
const PHRASES: Array<[RegExp, string]> = [
  [/\bgift\s*card(s)?\b/gi, "Tarjeta de regalo"],
  [/\bgiftcard(s)?\b/gi, "Tarjeta de regalo"],
  [/\bgift\s*pack\b/gi, "Paquete de regalo"],
  [/\bgiftpack\b/gi, "Paquete de regalo"],
  [/\bwallet\s*code\b/gi, "Código de saldo"],
  [/\bbattle\s*pass\b/gi, "Pase de batalla"],
  [/\bseason\s*pass\b/gi, "Pase de temporada"],
  [/\bweekly\s*pass\b/gi, "Pase semanal"],
  [/\bmonthly\s*pass\b/gi, "Pase mensual"],
  [/\bdaily\s*pass\b/gi, "Pase diario"],
  [/\bweekly\s*card\b/gi, "Tarjeta semanal"],
  [/\bmonthly\s*card\b/gi, "Tarjeta mensual"],
  [/\bgrowth\s*fund\b/gi, "Fondo de crecimiento"],
  [/\bmonthly\s*card\b/gi, "Tarjeta mensual"],
  [/\btop\s*up\b/gi, "Recarga"],
  [/\blevel\s*up\b/gi, "Subida de nivel"],
  [/\bsupply\s*pack\b/gi, "Paquete de suministros"],
  [/\bstarter\s*pack\b/gi, "Paquete inicial"],
  [/\bspecial\s*offer\b/gi, "Oferta especial"],
  [/\blimited\s*time\b/gi, "Tiempo limitado"],
  [/\bfirst\s*purchase\b/gi, "Primera compra"],
  [/\bdouble\s*rewards?\b/gi, "Recompensas dobles"],
  [/\bmembership\b/gi, "Membresía"],
  [/\bsubscription\b/gi, "Suscripción"],
];

// Palabras sueltas
const WORDS: Record<string, string> = {
  pack: "Paquete",
  package: "Paquete",
  packs: "Paquetes",
  bundle: "Paquete",
  box: "Caja",
  chest: "Cofre",
  card: "Tarjeta",
  cards: "Tarjetas",
  code: "Código",
  key: "Llave",
  ticket: "Ticket",
  tickets: "Tickets",
  voucher: "Vale",
  vouchers: "Vales",
  coins: "Monedas",
  coin: "Moneda",
  credits: "Créditos",
  points: "Puntos",
  token: "Token",
  tokens: "Tokens",
  gems: "Gemas",
  gem: "Gema",
  crystals: "Cristales",
  crystal: "Cristal",
  shards: "Fragmentos",
  shard: "Fragmento",
  stars: "Estrellas",
  star: "Estrella",
  ingots: "Lingotes",
  runes: "Runas",
  dice: "Dados",
  chips: "Fichas",
  opals: "Ópalos",
  opal: "Ópalo",
  ruby: "Rubí",
  jade: "Jade",
  crowns: "Coronas",
  stardust: "Polvo estelar",
  supply: "Suministro",
  supplies: "Suministros",
  rewards: "Recompensas",
  reward: "Recompensa",
  bonus: "Bono",
  benefit: "Beneficio",
  gift: "Regalo",
  discount: "Descuento",
  deal: "Oferta",
  offer: "Oferta",
  value: "Valor",
  special: "Especial",
  premium: "Premium",
  weekly: "Semanal",
  monthly: "Mensual",
  daily: "Diario",
  day: "Día",
  days: "Días",
  month: "Mes",
  months: "Meses",
  season: "Temporada",
  time: "Tiempo",
  limited: "Limitado",
  level: "Nivel",
  advanced: "Avanzado",
  adv: "Avanzado",
  upgrade: "Mejora",
  upgraded: "Mejorado",
  unlock: "Desbloqueo",
  growth: "Crecimiento",
  fund: "Fondo",
  progress: "Progreso",
  rental: "Alquiler",
  renew: "Renovación",
  plan: "Plan",
  selection: "Selección",
  selected: "Seleccionado",
  variant: "Variante",
  version: "Versión",
  set: "Set",
  kit: "Kit",
  module: "Módulo",
  core: "Núcleo",
  server: "Servidor",
  game: "Juego",
  player: "Jugador",
  person: "Persona",
  small: "Pequeño",
  big: "Grande",
  double: "Doble",
  twin: "Doble",
  new: "Nuevo",
  first: "Primera",
  more: "Más",
  less: "Menos",
  only: "Solo",
  handful: "Puñado",
  pile: "Montón",
  support: "Soporte",
  training: "Entrenamiento",
  research: "Investigación",
  recruit: "Reclutamiento",
  recruitment: "Reclutamiento",
  summon: "Invocación",
  summons: "Invocaciones",
  summoning: "Invocación",
  draw: "Tirada",
  mission: "Misión",
  achievement: "Logro",
  promotion: "Promoción",
  purchase: "Compra",
  redeem: "Canje",
  reserve: "Reserva",
  return: "Regreso",
  rate: "Tasa",
  equipment: "Equipamiento",
  weapon: "Arma",
  skill: "Habilidad",
  skin: "Aspecto",
  costume: "Atuendo",
  mount: "Montura",
  beast: "Bestia",
  hunter: "Cazador",
  master: "Maestro",
  officer: "Oficial",
  rookie: "Novato",
  elite: "Élite",
  legendary: "Legendario",
  epic: "Épico",
  rare: "Raro",
  exclusive: "Exclusivo",
  deluxe: "Deluxe",
  ultimate: "Definitivo",
  basic: "Básico",
  class: "Clase",
  golden: "Dorado",
  gold: "Oro",
  silver: "Plata",
  platinum: "Platino",
  divine: "Divino",
  holy: "Sagrado",
  sanctified: "Santificado",
  spiritual: "Espiritual",
  spirit: "Espíritu",
  soul: "Alma",
  blessing: "Bendición",
  radiance: "Resplandor",
  radiant: "Radiante",
  fortune: "Fortuna",
  lucky: "Afortunado",
  dream: "Sueño",
  memory: "Recuerdo",
  heart: "Corazón",
  heartfelt: "Sincero",
  bond: "Vínculo",
  vow: "Voto",
  wish: "Deseo",
  embrace: "Abrazo",
  story: "Historia",
  fantasy: "Fantasía",
  enchantment: "Encantamiento",
  ascension: "Ascensión",
  enhancement: "Mejora",
  treasure: "Tesoro",
  fire: "Fuego",
  water: "Agua",
  wind: "Viento",
  forest: "Bosque",
  moon: "Luna",
  night: "Noche",
  winter: "Invierno",
  summer: "Verano",
  spring: "Primavera",
  rainbow: "Arcoíris",
  flower: "Flor",
  blossom: "Floración",
  rose: "Rosa",
  lotus: "Loto",
  orchid: "Orquídea",
  butterfly: "Mariposa",
  fairy: "Hada",
  angel: "Ángel",
  devil: "Demonio",
  dragon: "Dragón",
  scarlet: "Escarlata",
  sparkle: "Destello",
  silent: "Silencioso",
  clear: "Claro",
  soaked: "Empapado",
  reverse: "Inverso",
  scale: "Escama",
  stamp: "Sello",
  stamina: "Energía",
  strike: "Golpe",
  association: "Asociación",
  combination: "Combinación",
  disciplinary: "Disciplinario",
  anniversary: "Aniversario",
  superstar: "Superestrella",
  starting: "Inicial",
  diamond: "Diamante",
  diamonds: "Diamantes",
};

const KEEP = new Set([
  "psn", "steam", "xbox", "itunes", "razer", "roblox", "robux", "valorant", "netflix",
  "google", "play", "amazon", "apple", "nintendo", "eshop", "telegram", "pubg", "uc",
  "vp", "fc", "mp", "lv", "vip", "apex", "riot", "honor", "kings", "nexus", "prime",
  "plus", "lite", "super", "ultra", "global", "android", "ios", "sentinel", "premiere",
  "anima", "agathion", "erythrina", "hydrangea", "marigold", "avacoins", "link",
]);

function applyCase(original: string, translated: string): string {
  if (original === original.toUpperCase() && original.length > 1) return translated.toUpperCase();
  if (original[0] === original[0]?.toUpperCase()) {
    return translated.charAt(0).toUpperCase() + translated.slice(1);
  }
  return translated.charAt(0).toLowerCase() + translated.slice(1);
}

export function translateOfferName(name: string | null | undefined): string {
  if (!name) return "";
  let out = name;

  for (const [pattern, replacement] of PHRASES) {
    out = out.replace(pattern, (match) => applyCase(match, replacement));
  }

  out = out.replace(/[A-Za-z]+/g, (word) => {
    const lower = word.toLowerCase();
    if (KEEP.has(lower)) return word;
    const translated = WORDS[lower];
    return translated ? applyCase(word, translated) : word;
  });

  return out.replace(/\s{2,}/g, " ").trim();
}
