/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComercioRouteImport } from './routes/comercio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecargasRouteImport } from './routes/recargas'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminComercioRouteImport } from './routes/admin/comercio'
import { Route as AdminConfiguracionRouteImport } from './routes/admin/configuracion'
import { Route as AdminDepositosRouteImport } from './routes/admin/depositos'
import { Route as AdminG2bulkRouteImport } from './routes/admin/g2bulk'
import { Route as AdminJuegosRouteImport } from './routes/admin/juegos'
import { Route as AdminPagosRouteImport } from './routes/admin/pagos'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminProductosRouteImport } from './routes/admin/productos'
import { Route as AdminReferidosRouteImport } from './routes/admin/referidos'
import { Route as AdminRetirosRouteImport } from './routes/admin/retiros'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppNotificacionesRouteImport } from './routes/app/notificaciones'
import { Route as AppPerfilRouteImport } from './routes/app/perfil'
import { Route as AppReferidosRouteImport } from './routes/app/referidos'
import { Route as JuegosIndexRouteImport } from './routes/juegos/index'
import { Route as JuegosSlugRouteImport } from './routes/juegos/$slug'
import { Route as AppComercioIndexRouteImport } from './routes/app/comercio/index'
import { Route as AppComercioIdRouteImport } from './routes/app/comercio/$id'
import { Route as AppComercioMisPublicacionesRouteImport } from './routes/app/comercio/mis-publicaciones'
import { Route as AppComercioPublicarRouteImport } from './routes/app/comercio/publicar'
import { Route as AppPedidosIndexRouteImport } from './routes/app/pedidos/index'
import { Route as AppPedidosIdRouteImport } from './routes/app/pedidos/$id'
import { Route as AppRecargasIndexRouteImport } from './routes/app/recargas/index'
import { Route as AppRecargasSlugRouteImport } from './routes/app/recargas/$slug'
import { Route as AppWalletIndexRouteImport } from './routes/app/wallet/index'
import { Route as AppWalletDepositarRouteImport } from './routes/app/wallet/depositar'
import { Route as AppWalletRetirarRouteImport } from './routes/app/wallet/retirar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercioRoute = ComercioRouteImport.update({
  id: '/comercio',
  path: '/comercio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecargasRoute = RecargasRouteImport.update({
  id: '/recargas',
  path: '/recargas',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComercioRoute = AdminComercioRouteImport.update({
  id: '/admin/comercio',
  path: '/admin/comercio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/admin/configuracion',
  path: '/admin/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepositosRoute = AdminDepositosRouteImport.update({
  id: '/admin/depositos',
  path: '/admin/depositos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminG2bulkRoute = AdminG2bulkRouteImport.update({
  id: '/admin/g2bulk',
  path: '/admin/g2bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJuegosRoute = AdminJuegosRouteImport.update({
  id: '/admin/juegos',
  path: '/admin/juegos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagosRoute = AdminPagosRouteImport.update({
  id: '/admin/pagos',
  path: '/admin/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/admin/productos',
  path: '/admin/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReferidosRoute = AdminReferidosRouteImport.update({
  id: '/admin/referidos',
  path: '/admin/referidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRetirosRoute = AdminRetirosRouteImport.update({
  id: '/admin/retiros',
  path: '/admin/retiros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/admin/wallets',
  path: '/admin/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificacionesRoute = AppNotificacionesRouteImport.update({
  id: '/app/notificaciones',
  path: '/app/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/app/perfil',
  path: '/app/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReferidosRoute = AppReferidosRouteImport.update({
  id: '/app/referidos',
  path: '/app/referidos',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegosIndexRoute = JuegosIndexRouteImport.update({
  id: '/juegos/',
  path: '/juegos/',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegosSlugRoute = JuegosSlugRouteImport.update({
  id: '/juegos/$slug',
  path: '/juegos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppComercioIndexRoute = AppComercioIndexRouteImport.update({
  id: '/app/comercio/',
  path: '/app/comercio/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppComercioIdRoute = AppComercioIdRouteImport.update({
  id: '/app/comercio/$id',
  path: '/app/comercio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppComercioMisPublicacionesRoute =
  AppComercioMisPublicacionesRouteImport.update({
    id: '/app/comercio/mis-publicaciones',
    path: '/app/comercio/mis-publicaciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppComercioPublicarRoute = AppComercioPublicarRouteImport.update({
  id: '/app/comercio/publicar',
  path: '/app/comercio/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPedidosIndexRoute = AppPedidosIndexRouteImport.update({
  id: '/app/pedidos/',
  path: '/app/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPedidosIdRoute = AppPedidosIdRouteImport.update({
  id: '/app/pedidos/$id',
  path: '/app/pedidos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecargasIndexRoute = AppRecargasIndexRouteImport.update({
  id: '/app/recargas/',
  path: '/app/recargas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecargasSlugRoute = AppRecargasSlugRouteImport.update({
  id: '/app/recargas/$slug',
  path: '/app/recargas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletIndexRoute = AppWalletIndexRouteImport.update({
  id: '/app/wallet/',
  path: '/app/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletDepositarRoute = AppWalletDepositarRouteImport.update({
  id: '/app/wallet/depositar',
  path: '/app/wallet/depositar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRetirarRoute = AppWalletRetirarRouteImport.update({
  id: '/app/wallet/retirar',
  path: '/app/wallet/retirar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comercio': typeof ComercioRoute
  '/login': typeof LoginRoute
  '/recargas': typeof RecargasRoute
  '/registro': typeof RegistroRoute
  '/admin/comercio': typeof AdminComercioRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/depositos': typeof AdminDepositosRoute
  '/admin/g2bulk': typeof AdminG2bulkRoute
  '/admin/juegos': typeof AdminJuegosRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/referidos': typeof AdminReferidosRoute
  '/admin/retiros': typeof AdminRetirosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/app/notificaciones': typeof AppNotificacionesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/referidos': typeof AppReferidosRoute
  '/juegos/$slug': typeof JuegosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/juegos/': typeof JuegosIndexRoute
  '/app/comercio/$id': typeof AppComercioIdRoute
  '/app/comercio/mis-publicaciones': typeof AppComercioMisPublicacionesRoute
  '/app/comercio/publicar': typeof AppComercioPublicarRoute
  '/app/pedidos/$id': typeof AppPedidosIdRoute
  '/app/recargas/$slug': typeof AppRecargasSlugRoute
  '/app/wallet/depositar': typeof AppWalletDepositarRoute
  '/app/wallet/retirar': typeof AppWalletRetirarRoute
  '/app/comercio/': typeof AppComercioIndexRoute
  '/app/pedidos/': typeof AppPedidosIndexRoute
  '/app/recargas/': typeof AppRecargasIndexRoute
  '/app/wallet/': typeof AppWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comercio': typeof ComercioRoute
  '/login': typeof LoginRoute
  '/recargas': typeof RecargasRoute
  '/registro': typeof RegistroRoute
  '/admin/comercio': typeof AdminComercioRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/depositos': typeof AdminDepositosRoute
  '/admin/g2bulk': typeof AdminG2bulkRoute
  '/admin/juegos': typeof AdminJuegosRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/referidos': typeof AdminReferidosRoute
  '/admin/retiros': typeof AdminRetirosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/app/notificaciones': typeof AppNotificacionesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/referidos': typeof AppReferidosRoute
  '/juegos/$slug': typeof JuegosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/juegos': typeof JuegosIndexRoute
  '/app/comercio/$id': typeof AppComercioIdRoute
  '/app/comercio/mis-publicaciones': typeof AppComercioMisPublicacionesRoute
  '/app/comercio/publicar': typeof AppComercioPublicarRoute
  '/app/pedidos/$id': typeof AppPedidosIdRoute
  '/app/recargas/$slug': typeof AppRecargasSlugRoute
  '/app/wallet/depositar': typeof AppWalletDepositarRoute
  '/app/wallet/retirar': typeof AppWalletRetirarRoute
  '/app/comercio': typeof AppComercioIndexRoute
  '/app/pedidos': typeof AppPedidosIndexRoute
  '/app/recargas': typeof AppRecargasIndexRoute
  '/app/wallet': typeof AppWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comercio': typeof ComercioRoute
  '/login': typeof LoginRoute
  '/recargas': typeof RecargasRoute
  '/registro': typeof RegistroRoute
  '/admin/comercio': typeof AdminComercioRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/depositos': typeof AdminDepositosRoute
  '/admin/g2bulk': typeof AdminG2bulkRoute
  '/admin/juegos': typeof AdminJuegosRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/referidos': typeof AdminReferidosRoute
  '/admin/retiros': typeof AdminRetirosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/app/notificaciones': typeof AppNotificacionesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/referidos': typeof AppReferidosRoute
  '/juegos/$slug': typeof JuegosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/juegos/': typeof JuegosIndexRoute
  '/app/comercio/$id': typeof AppComercioIdRoute
  '/app/comercio/mis-publicaciones': typeof AppComercioMisPublicacionesRoute
  '/app/comercio/publicar': typeof AppComercioPublicarRoute
  '/app/pedidos/$id': typeof AppPedidosIdRoute
  '/app/recargas/$slug': typeof AppRecargasSlugRoute
  '/app/wallet/depositar': typeof AppWalletDepositarRoute
  '/app/wallet/retirar': typeof AppWalletRetirarRoute
  '/app/comercio/': typeof AppComercioIndexRoute
  '/app/pedidos/': typeof AppPedidosIndexRoute
  '/app/recargas/': typeof AppRecargasIndexRoute
  '/app/wallet/': typeof AppWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comercio'
    | '/login'
    | '/recargas'
    | '/registro'
    | '/admin/comercio'
    | '/admin/configuracion'
    | '/admin/depositos'
    | '/admin/g2bulk'
    | '/admin/juegos'
    | '/admin/pagos'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/referidos'
    | '/admin/retiros'
    | '/admin/usuarios'
    | '/admin/wallets'
    | '/app/notificaciones'
    | '/app/perfil'
    | '/app/referidos'
    | '/juegos/$slug'
    | '/admin/'
    | '/app/'
    | '/juegos/'
    | '/app/comercio/$id'
    | '/app/comercio/mis-publicaciones'
    | '/app/comercio/publicar'
    | '/app/pedidos/$id'
    | '/app/recargas/$slug'
    | '/app/wallet/depositar'
    | '/app/wallet/retirar'
    | '/app/comercio/'
    | '/app/pedidos/'
    | '/app/recargas/'
    | '/app/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comercio'
    | '/login'
    | '/recargas'
    | '/registro'
    | '/admin/comercio'
    | '/admin/configuracion'
    | '/admin/depositos'
    | '/admin/g2bulk'
    | '/admin/juegos'
    | '/admin/pagos'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/referidos'
    | '/admin/retiros'
    | '/admin/usuarios'
    | '/admin/wallets'
    | '/app/notificaciones'
    | '/app/perfil'
    | '/app/referidos'
    | '/juegos/$slug'
    | '/admin'
    | '/app'
    | '/juegos'
    | '/app/comercio/$id'
    | '/app/comercio/mis-publicaciones'
    | '/app/comercio/publicar'
    | '/app/pedidos/$id'
    | '/app/recargas/$slug'
    | '/app/wallet/depositar'
    | '/app/wallet/retirar'
    | '/app/comercio'
    | '/app/pedidos'
    | '/app/recargas'
    | '/app/wallet'
  id:
    | '__root__'
    | '/'
    | '/comercio'
    | '/login'
    | '/recargas'
    | '/registro'
    | '/admin/comercio'
    | '/admin/configuracion'
    | '/admin/depositos'
    | '/admin/g2bulk'
    | '/admin/juegos'
    | '/admin/pagos'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/referidos'
    | '/admin/retiros'
    | '/admin/usuarios'
    | '/admin/wallets'
    | '/app/notificaciones'
    | '/app/perfil'
    | '/app/referidos'
    | '/juegos/$slug'
    | '/admin/'
    | '/app/'
    | '/juegos/'
    | '/app/comercio/$id'
    | '/app/comercio/mis-publicaciones'
    | '/app/comercio/publicar'
    | '/app/pedidos/$id'
    | '/app/recargas/$slug'
    | '/app/wallet/depositar'
    | '/app/wallet/retirar'
    | '/app/comercio/'
    | '/app/pedidos/'
    | '/app/recargas/'
    | '/app/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComercioRoute: typeof ComercioRoute
  LoginRoute: typeof LoginRoute
  RecargasRoute: typeof RecargasRoute
  RegistroRoute: typeof RegistroRoute
  AdminComercioRoute: typeof AdminComercioRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminDepositosRoute: typeof AdminDepositosRoute
  AdminG2bulkRoute: typeof AdminG2bulkRoute
  AdminJuegosRoute: typeof AdminJuegosRoute
  AdminPagosRoute: typeof AdminPagosRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminReferidosRoute: typeof AdminReferidosRoute
  AdminRetirosRoute: typeof AdminRetirosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AppNotificacionesRoute: typeof AppNotificacionesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppReferidosRoute: typeof AppReferidosRoute
  JuegosSlugRoute: typeof JuegosSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppIndexRoute: typeof AppIndexRoute
  JuegosIndexRoute: typeof JuegosIndexRoute
  AppComercioIdRoute: typeof AppComercioIdRoute
  AppComercioMisPublicacionesRoute: typeof AppComercioMisPublicacionesRoute
  AppComercioPublicarRoute: typeof AppComercioPublicarRoute
  AppPedidosIdRoute: typeof AppPedidosIdRoute
  AppRecargasSlugRoute: typeof AppRecargasSlugRoute
  AppWalletDepositarRoute: typeof AppWalletDepositarRoute
  AppWalletRetirarRoute: typeof AppWalletRetirarRoute
  AppComercioIndexRoute: typeof AppComercioIndexRoute
  AppPedidosIndexRoute: typeof AppPedidosIndexRoute
  AppRecargasIndexRoute: typeof AppRecargasIndexRoute
  AppWalletIndexRoute: typeof AppWalletIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercio': {
      id: '/comercio'
      path: '/comercio'
      fullPath: '/comercio'
      preLoaderRoute: typeof ComercioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recargas': {
      id: '/recargas'
      path: '/recargas'
      fullPath: '/recargas'
      preLoaderRoute: typeof RecargasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/comercio': {
      id: '/admin/comercio'
      path: '/admin/comercio'
      fullPath: '/admin/comercio'
      preLoaderRoute: typeof AdminComercioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/admin/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/depositos': {
      id: '/admin/depositos'
      path: '/admin/depositos'
      fullPath: '/admin/depositos'
      preLoaderRoute: typeof AdminDepositosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/g2bulk': {
      id: '/admin/g2bulk'
      path: '/admin/g2bulk'
      fullPath: '/admin/g2bulk'
      preLoaderRoute: typeof AdminG2bulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/juegos': {
      id: '/admin/juegos'
      path: '/admin/juegos'
      fullPath: '/admin/juegos'
      preLoaderRoute: typeof AdminJuegosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pagos': {
      id: '/admin/pagos'
      path: '/admin/pagos'
      fullPath: '/admin/pagos'
      preLoaderRoute: typeof AdminPagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/admin/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/referidos': {
      id: '/admin/referidos'
      path: '/admin/referidos'
      fullPath: '/admin/referidos'
      preLoaderRoute: typeof AdminReferidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/retiros': {
      id: '/admin/retiros'
      path: '/admin/retiros'
      fullPath: '/admin/retiros'
      preLoaderRoute: typeof AdminRetirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/admin/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notificaciones': {
      id: '/app/notificaciones'
      path: '/app/notificaciones'
      fullPath: '/app/notificaciones'
      preLoaderRoute: typeof AppNotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/app/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/referidos': {
      id: '/app/referidos'
      path: '/app/referidos'
      fullPath: '/app/referidos'
      preLoaderRoute: typeof AppReferidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juegos/': {
      id: '/juegos/'
      path: '/juegos'
      fullPath: '/juegos/'
      preLoaderRoute: typeof JuegosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juegos/$slug': {
      id: '/juegos/$slug'
      path: '/juegos/$slug'
      fullPath: '/juegos/$slug'
      preLoaderRoute: typeof JuegosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/comercio/': {
      id: '/app/comercio/'
      path: '/app/comercio'
      fullPath: '/app/comercio/'
      preLoaderRoute: typeof AppComercioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/comercio/$id': {
      id: '/app/comercio/$id'
      path: '/app/comercio/$id'
      fullPath: '/app/comercio/$id'
      preLoaderRoute: typeof AppComercioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/comercio/mis-publicaciones': {
      id: '/app/comercio/mis-publicaciones'
      path: '/app/comercio/mis-publicaciones'
      fullPath: '/app/comercio/mis-publicaciones'
      preLoaderRoute: typeof AppComercioMisPublicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/comercio/publicar': {
      id: '/app/comercio/publicar'
      path: '/app/comercio/publicar'
      fullPath: '/app/comercio/publicar'
      preLoaderRoute: typeof AppComercioPublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pedidos/': {
      id: '/app/pedidos/'
      path: '/app/pedidos'
      fullPath: '/app/pedidos/'
      preLoaderRoute: typeof AppPedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pedidos/$id': {
      id: '/app/pedidos/$id'
      path: '/app/pedidos/$id'
      fullPath: '/app/pedidos/$id'
      preLoaderRoute: typeof AppPedidosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/recargas/': {
      id: '/app/recargas/'
      path: '/app/recargas'
      fullPath: '/app/recargas/'
      preLoaderRoute: typeof AppRecargasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/recargas/$slug': {
      id: '/app/recargas/$slug'
      path: '/app/recargas/$slug'
      fullPath: '/app/recargas/$slug'
      preLoaderRoute: typeof AppRecargasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wallet/': {
      id: '/app/wallet/'
      path: '/app/wallet'
      fullPath: '/app/wallet/'
      preLoaderRoute: typeof AppWalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wallet/depositar': {
      id: '/app/wallet/depositar'
      path: '/app/wallet/depositar'
      fullPath: '/app/wallet/depositar'
      preLoaderRoute: typeof AppWalletDepositarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wallet/retirar': {
      id: '/app/wallet/retirar'
      path: '/app/wallet/retirar'
      fullPath: '/app/wallet/retirar'
      preLoaderRoute: typeof AppWalletRetirarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComercioRoute: ComercioRoute,
  LoginRoute: LoginRoute,
  RecargasRoute: RecargasRoute,
  RegistroRoute: RegistroRoute,
  AdminComercioRoute: AdminComercioRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminDepositosRoute: AdminDepositosRoute,
  AdminG2bulkRoute: AdminG2bulkRoute,
  AdminJuegosRoute: AdminJuegosRoute,
  AdminPagosRoute: AdminPagosRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminReferidosRoute: AdminReferidosRoute,
  AdminRetirosRoute: AdminRetirosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AppNotificacionesRoute: AppNotificacionesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppReferidosRoute: AppReferidosRoute,
  JuegosSlugRoute: JuegosSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppIndexRoute: AppIndexRoute,
  JuegosIndexRoute: JuegosIndexRoute,
  AppComercioIdRoute: AppComercioIdRoute,
  AppComercioMisPublicacionesRoute: AppComercioMisPublicacionesRoute,
  AppComercioPublicarRoute: AppComercioPublicarRoute,
  AppPedidosIdRoute: AppPedidosIdRoute,
  AppRecargasSlugRoute: AppRecargasSlugRoute,
  AppWalletDepositarRoute: AppWalletDepositarRoute,
  AppWalletRetirarRoute: AppWalletRetirarRoute,
  AppComercioIndexRoute: AppComercioIndexRoute,
  AppPedidosIndexRoute: AppPedidosIndexRoute,
  AppRecargasIndexRoute: AppRecargasIndexRoute,
  AppWalletIndexRoute: AppWalletIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
